# Generated by Django 4.1.4 on 2023-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('m', models.IntegerField()),
            ],
        ),
    ]
